version: '2'
services:

  docker-registry:
    image: registry
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    ports:
      - 127.0.0.1:${PORT}:5000
    volumes:
      - docker-registry:/var/lib/registry

