version: '2'
services:
  cloudflare-dyndns:
    image: ellerbrock/alpine-cloudflare-dyndns
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      com.socialengine.rancher-cron.schedule: '@every 5m'
      com.frapsoft.container.cleanup: 'false'
      com.frapsoft.container.tag: 'frapcloud'
    environment:
        CF_EMAIL: ${CF_EMAIL}
        CF_TOKEN: ${CF_TOKEN}
        CF_ZONE_NAME: ${CF_ZONE_NAME}
        CF_DOMAIN_NAME: ${CF_DOMAIN_NAME}

